name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
       # plan: 
       #   - { build: stack, resolver: "--resolver lts-15"  }

    runs-on: ${{ matrix.os }}

    steps:

    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Cache ~/.local/bin
      uses: actions/cache@v1
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-local-bin

    - name: Cache .stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work

    - name: Check out
      uses: actions/checkout@v2

    - name: Install stack (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        stack --version

    - name: Install stack (mac)
      if: matrix.os == 'macos-latest'
      run: |
        brew install haskell-stack
        stack --version
    - name: Install stack (windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -skL -o stack.zip http://www.stackage.org/stack/windows-x86_64
        7z x stack.zip -oC:\Windows stack.exe
        stack --version
    - name: Install GHC
      run: |
        stack setup $ARGS
    - name: Install haskell deps
      run: |
        stack --install-ghc $ARGS test --bench --only-dependencies
      env:
        ARGS: ${{ matrix.plan.resolver }}
        # BUILD: ${{ matrix.plan.build }}

    - name: Build hledger
      run: |
        stack $ARGS install --ghc-options=-Werror --test --bench --no-run-benchmarks --haddock --no-haddock-deps
      #  stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        ARGS: ${{ matrix.plan.resolver }}

    - name: Haskell Linter
      # You may pin to the exact commit or the version.
      # uses: domdere/haskell-lint-action@f865aa0bfb6db9632e0f905dee4b0716a76a5494
      uses: domdere/haskell-lint-action@v1.0.2
    - name: Build generator
      run: cd generator && stack build
